### ISSUE TITLE
Performing Hard drop after T-spin invalidates T-spin

### ISSUE THREAD

**Issue by bmjeon5957** [Porowl/JS-PPT#5]
// Stage.js : Line 156
`piece.lastMove = LAST_MOVE.DOWN`

Was the cause of Invalid T-spin ( #1 ), Which i thought was gone but still persists.
Deleting Line 156 in Stage.js solves the problem, And as far as I'm aware, I'm not seeing any use of `LAST_MOVE.DOWN` being used elsewhere and `LAST_MOVE.SPIN` only being used for checking t-spin while `LAST_MOVE.MOVE` already resetting the spin check, I expect no immediate side effect but you probably would want differnet kind of solution, up to you though.

**Comment by Porowl** [comment]
Line 156 was added to prevent invalid T-Spins being detected as valid ones. Previously spinning T mino and then performing hard drop was detected as t-spin if three of four corners were filled at the point it lands. Though T-spin detection mechanism would have to be adjusted for accuracy, for now the line will be adjusted so that performing harddrop to lock the piece wouldn't affect the status.

```JavaScript
piece.lastMove = LAST_MOVE.DOWN

//is changed to

if(counter!=0) piece.lastMove = LAST_MOVE.MOVE
```
